Controllers/LoginController.cs
using Milestone.Models;
using Milestone.Services;
using Microsoft.AspNetCore.Mvc;
using Activity_2_RegisterAndLoginApp.Utility;

namespace Milestone.Controllers
{
    public class LoginController : Controller
    {

        public ILoggers Logger { get; set; }

        public LoginController(ILoggers loggers)
        {
            Logger = loggers;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProcessLogin(UserModel user)
        {
            Logger.Info("Entering The ProcessLogin Method");
            SecurityService securityService = new SecurityService();

            if(securityService.IsValid(user))
            {
				HttpContext.Session.SetString("username", user.UserName);
                Logger.Info($"{user.UserName} is Valid");
				return RedirectToAction("Index", "game");
            }
            else
            {
                Logger.Error("Login Failed.");
				return View("LoginFailure", user);
            }
        }
    }
}

Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Milestone.Models;
using Milestone.Services;

namespace Activity_2_RegisterAndLoginApp.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProcessRegistration(UserModel user)
        {
            SecurityService securityService = new SecurityService();

            if (securityService.AddUser(user))
            {
                return RedirectToAction("Index", "game");
            }
            else
            {
                return View("RegistrationFailure", user);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Milestone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Milestone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
    @Html.Partial("_navbar.cshtml")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Milestone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Milestone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>