Controllers/GameController.cs
using Activity_2_RegisterAndLoginApp.Controllers;
using Activity_2_RegisterAndLoginApp.Models;
using Activity_2_RegisterAndLoginApp.Services;
using Activity_2_RegisterAndLoginApp.Utility;
using Microsoft.AspNetCore.Mvc;
using Milestone.Models;
using System.Security.Cryptography.X509Certificates;

namespace Milestone.Controllers
{
    public class GameController : Controller
    {
        public ILoggers Logger { get; set; }

        public static Board gameboard;
        public static GameBoardService boardService;
		public static SaveGameService saveGameService;

<<<<<<< Updated upstream
		[HttpGet]
		[CustomAuthorization]
		public IActionResult Index()
=======
        public GameController(ILoggers loggers)
>>>>>>> Stashed changes
        {
            Logger = loggers;
        }

        [HttpGet]
		[CustomAuthorization]
		public IActionResult Index()
        {

			Logger.Info("Game has been created");
            gameboard = new Board(10, .1f);
            boardService = new GameBoardService(gameboard);
            boardService.setupBombs();
            boardService.CalcLiveNeighbors();
			saveGameService = new SaveGameService();
            return View("Index", gameboard);
        }

<<<<<<< Updated upstream
        [HttpGet]
=======
        [HttpPost]
>>>>>>> Stashed changes
        [CustomAuthorization]
        public IActionResult saveGame()
		{
			Logger.Info("Game has been saved");
			string username = HttpContext.Session.GetString("username") ?? ""; 			
			saveGameService.saveGame(username, gameboard);

			return PartialView("_SaveGamePartial");
		}

<<<<<<< Updated upstream
        [HttpGet]
=======
        [HttpPost]
>>>>>>> Stashed changes
        [CustomAuthorization]
        public IActionResult viewGames()
		{
			string username = HttpContext.Session.GetString("username") ?? "";
			List<GameModel> games = saveGameService.getUserGames(username);
			
			// Testing data to be removed


			return PartialView("ViewGames", games);
		}

<<<<<<< Updated upstream
        [HttpGet]
=======
        [HttpPost]
>>>>>>> Stashed changes
        [CustomAuthorization]
        public IActionResult loadGame(int id)
		{
			Logger.Info("Game has been loaded");
			GameModel game = saveGameService.getGameById(id);

			gameboard = saveGameService.deserialize(game.gameData);
			boardService = new GameBoardService(gameboard);
			boardService.CalcLiveNeighbors();
			return PartialView("_GridCellPartial", gameboard);
		}

<<<<<<< Updated upstream
        [HttpGet]
=======
        [HttpPost]
>>>>>>> Stashed changes
        [CustomAuthorization]
        public IActionResult deleteGame(int id)
		{
			string username = HttpContext.Session.GetString("username") ?? "";
			saveGameService.deleteGame(id);

			return PartialView("_GridCellPartial", gameboard);
		}

<<<<<<< Updated upstream
        [HttpGet]
=======
        [HttpPost]
>>>>>>> Stashed changes
        [CustomAuthorization]
        public IActionResult leftClick(int col, int row)
		{
			boardService.leftClick(col, row);
			if (boardService.checkForLose())
			{

				return PartialView("EndGame");

			}
			else if (boardService.checkForWin())
			{
				return PartialView("Victory");
			}
			else
			{
				return PartialView("_GridCellPartial", gameboard);
			}
		}

<<<<<<< Updated upstream
        [HttpGet]
=======
        [HttpPost]
>>>>>>> Stashed changes
        [CustomAuthorization]
        public IActionResult rightClick(int col, int row)
		{
			boardService.rightClick(col, row);

			return PartialView("_GridCellPartial", gameboard);
		}
	}
}

Views/Game/Endgame.cshtml
<div>
    <h4>Game Over, Try again!</h4>
</div>
<div>
    <a asp-action="Index">New Game</a>
</div>

Views/Game/Index.cshtml
@model Milestone.Models.Board
<script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>

<script src="/js/Game.js"></script>
<style>
	button {
		border: none;
	}
</style>
<p>Current Time: @DateTime.Now</p>
<div id="board" class="row">
    <div class="col">
        <table>
            @for (var i = 0; i < Model.Size; i++)
		{
            <tr>
                @for (var j = 0; j < Model.Size; j++)
				{
                <td>
                    <form>
                        <input name="col" value="@Model.Grid[i,j].Row" hidden>
                        <input name="row" value="@Model.Grid[i,j].Col" hidden>
                        <div class="oneCell" id=@i@j>
                            <button class="game-cell" type="submit" data-col="@Model.Grid[i,j].Row" data-row="@Model.Grid[i,j].Col">
                                @if (Model.Grid[i, j].IsVisited == true)
									{
                                <img src="/img/visitedSquare.png" width="70px" height="70px">
									}
									else
									{
                                <img src="/img/square.jpeg" width="70px" height="70px">
									}

                            </button>
                        </div>
                    </form>

                </td>
				}
            </tr>
			}
        </table>
    </div>
    <div class="col">
        <form>
            <button type="submit" class="btn btn-primary save-btn" id="save-button">Save Game</button>
        </form>
        <div class="col" id="save-message">
            <p></p>
        </div>
    </div>
    <div class="col viewGamesButton">
        <form>
            <button type="submit" class="btn btn-primary view-btn" id="view-button">View Games</button>
        </form>
    </div>
</div>

Views/Game/Play.cshtml
<h1>Welcome Back!</h1>

<div class="row">
    <div class="col">
        <a class="btn btn-primary">Play New</a>
    </div>
</div>

Views/Game/Victory.cshtml
<div>
    <h4>You win! Great Job!</h4>
</div>
<div>
    <a asp-action="Index">New Game</a>
</div>

Views/Game/_GridCellPartial.cshtml
@model Milestone.Models.Board
<style>
	.game-cell {
		position: relative;
		text-align: center;
	}
	.liveNeighbors {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);

	}
</style>
<div class="row">
	<div class="col">
	<table>
		@for (var i = 0; i < Model.Size; i++)
		{
			<tr>
				@for (var j = 0; j < Model.Size; j++)
				{
					<td>
						<form>
							<input name="col" value="@Model.Grid[i,j].Row" hidden>
							<input name="row" value="@Model.Grid[i,j].Col" hidden>
							<div class="oneCell" id=@i@j>
								<button class="game-cell" type="submit" asp-controller="Game" asp-action="leftClick" data-col="@Model.Grid[i,j].Row" data-row="@Model.Grid[i,j].Col">
									@if (Model.Grid[i, j].IsVisited == true)
									{
										<img src="/img/visitedSquare.png" width="70px" height="70px">
											@if(Model.Grid[i,j].LiveNeighbors > 0)
											{
													<h2 class="liveNeighbors text-white">@Model.Grid[i,j].LiveNeighbors</h2>
											}
											
									}
									else if (Model.Grid[i, j].IsFlagged == true)
									{
										<img src="/img/flag.jpg" width="70px" height="70px">
									}
									else
									{
										<img src="/img/square.jpeg" width="70px" height="70px">
									}

								</button>
							</div>
						</form>

					</td>
				}
			</tr>
		}
	</table>
	</div>
	<div class="col">
		<form>
		<button type="submit" class="btn btn-primary save-btn" id="save-button">Save Game</button>
		</form>
		<div class="col" id="save-message">
			<p></p>
		</div>
	</div>
	<div class="col viewGamesButton">
		<form>
			<button type="submit" class="btn btn-primary view-btn" id="view-button">View Games</button>
		</form>
	</div>
</div>

Views/Game/_SaveGamePartial.cshtml
<div class="col">
    <p>Game Saved!</p>
</div>

Views/Game/viewGames.cshtml
@model IEnumerable<Activity_2_RegisterAndLoginApp.Models.GameModel>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
                <td>
                    <form>
                        <input name="id" value="@item.id" hidden/>
                        <button type="submit" class="btn btn-primary load-btn" data-id="@item.id" id="load-button">Load Game</button>
                    </form>
                    <form>
                        <input name="id" value="@item.id" hidden />
                        <button type="button" class="btn btn-primary delete-btn" data-id="@item.id">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>